version: '2'

services:
  # web with xhprof - dropteam images
  xhprof:
    # dropteam/drupal-php available tags: 7.0-apache, 5.6-apache
    image: dropteam/drupal-php:7.1-apache-xhprof

    ports:
      - "${PORT_WEBXHPROF}:80"
    environment:
      - SERVERNAME=${XHPROF_SERVERNAME}
      - SERVERALIAS=${XHPROF_SERVERALIAS}
      - DOCUMENTROOT=${DOCUMENTROOT}
    volumes:
      - ${LOCALPATH}:/var/www/html/:delegated
    depends_on:
      - database
      - mailhog
      - memcache
      - mongo
    links:
      - database:mysql
      - mailhog
      - memcache
      - mongo
    tty: true

  # mongodb container - dropteam images
  mongo:
    image: mongo:latest

  # xhgui container - dropteam images
  xhgui:
    image: dropteam/xhgui
    ports:
      - "${PORT_XHGUI}:80"
    depends_on:
      - mongo
    links:
      - mongo